// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlgefw9Gj8xkKTBZc9mX9MY7zvo6d6Ig',
    appId: '1:611301557128:web:f4b6119611aa713571f03d',
    messagingSenderId: '611301557128',
    projectId: 'haijuga-dkm',
    authDomain: 'haijuga-dkm.firebaseapp.com',
    storageBucket: 'haijuga-dkm.firebasestorage.app',
    measurementId: 'G-EPNT1MN4M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVLcMswTHOX6FVBmTMYZkHXgjWTzWuA8',
    appId: '1:611301557128:android:8340bf2d02a95f3671f03d',
    messagingSenderId: '611301557128',
    projectId: 'haijuga-dkm',
    storageBucket: 'haijuga-dkm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPOae-DawzUCr07Plzp8kSJnDxCFTJ0ms',
    appId: '1:611301557128:ios:d3dc1004089d279171f03d',
    messagingSenderId: '611301557128',
    projectId: 'haijuga-dkm',
    storageBucket: 'haijuga-dkm.firebasestorage.app',
    iosBundleId: 'com.dekulmen.haijuga',
  );
}
